#!/usr/bin/expect -f

# procedure to attempt connecting; result 0 if OK, 1 otherwise
proc connect {} {
  expect {
    "*password:*" {
      # grab the password
      stty -echo
      expect_user -re "(.*)\n"
      send_user "\n"
      stty echo
      set passwd $expect_out(1,string)
      send "$passwd\r"
      expect {
        "*hasenov-virtual-machine%*" {
          return 0
        }
      }
    }
  }
  # timed out
  return 1
}
 
#set timeout -1                                                                  
spawn ssh hasenov@10.100.1.1
match_max 100000

set ret [connect]
if { $ret == 0 } {
  send "cd zebralite\r"
  send "git push\r"
  expect "Username*"
  expect_user -re "(.*)\n"
  send_user "\n"
  set github_user $expect_out(1,string)
  send "$github_user\r"
  expect "Password*"
  stty -echo
  expect_user -re "(.*)\n"
  send_user "\n"
  stty echo
  set github_pass $expect_out(1,string)
  send "$github_pass\r"
  expect "*hasenov-virtual-machine%"
  send "exit\r"
  expect eof 
  exit 0
}
puts "\nError connecting to server\n"
exit 1
